server:
  port: 9000
spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/icodesoft/microservice-config
          default-label: main
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
management:
  endpoint:
    health:
      show-details: always